### ISSUE TITLE
Estruturar o pipeline de criação das tags e disponibilização da última release gerada para download.

### ISSUE THREAD

**Issue by Eduardojvr** [unbgames/unbgames#31]
Este script deve rodar do lado dos desenvolvedores, template disponível [aqui](https://github.com/unbgames/game-template)
**Tarefas**

- [x] Script para a criação das tags 
- [x] Disponibilizar o arquivo gerado pelo empacotamento para download

**Critérios de aceitação**

- [x] Criação automática das tags e disponibilização do arquivo gerado pelo empacotamento para download.

**Comment by lugope** [comment]
A criação de tags será feita por quem está contribuindo com o repositório, mas assim que o commit com tag for enviado para o repositório o empacotamento do jogo e a disponibilização dele será automatizada no Travis.
