### ISSUE TITLE
[Clean Code] - Aplicar técnicas nos templates da aplicação Vue

### ISSUE THREAD

**Issue by MarianaPicolo** [unbgames/unbgames#64]
Aplicar técnicas em toda a aplicação Vue.

- [x] Aplicar técnicas nos templates:
  - [x] CSS
  - [x] JavaScript

**Critérios de aceitação**

- [x] Todas as tarefas finalizadas.

**Comment by zero101010** [comment]
Foram aplicadas técnicas de clean code,no entando técnicas de solid no contexto do Vue não foi possível ser implementado,levando em consideração a estrutura de componentes utilizados pelo vue,uma alternativa seria utilizar outro Framework mas estruturado,como React ou angular, pois ambos possuem uma Orientação a objeto bem definida fazendo assim com que a utilização do solid seja possível.
