### ISSUE TITLE
Melhorar o componente hero da página inicial

### ISSUE THREAD

**Issue by ednunes** [unbgames/unbgames#7]
Atualmente, o componente hero que está na página inicial da aplicação está bem simples. A ideia é criar um componente que contenha mais infomações ou que seja um carrousel com os jogos de destaque da aplicação.

**Comment by MarianaPicolo** [comment]
Eu e o @zero101010 acabamos dividindo essa issue em duas, uma parte para a _homepage_, e outra para a página do _game_ em si.
A ideia inicial é padronizar o estilo da aplicação a partir de um protótipo de baixa fidelidade feito por ambos.
